spring.application.name=api.biblioteca
# Configuração do DataSource para MySQL
spring.datasource.url=jdbc:mysql://localhost:porta/bancodedados
spring.datasource.username=usuario
spring.datasource.password=senha
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuração do JPA/Hibernate
# O ddl-auto deve ser 'update' em produção, ou 'create-drop'/'create' para desenvolvimento/testes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect